sudo: required
services:
  - docker

before_install:
  - docker build -t bpc1985/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run bpc1985/react-test npm run test -- --coverage

after_success:
  - docker build -t bpc1985/multi-client ./client
  - docker build -t bpc1985/multi-nginx  ./nginx
  - docker build -t bpc1985/multi-server ./server
  - docker build -t bpc1985/multi-worker ./worker
  # Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images to push to docker hub
  - docker push bpc1985/multi-client
  - docker push bpc1985/multi-nginx
  - docker push bpc1985/multi-server
  - docker push bpc1985/multi-worker

deploy:
  provider: elasticbeanstalk
    region: "us-east-2"
    app: "multi-docker"
    env: "MultiDocker-env"
    bucket_name: "elasticbeanstalk-us-east-2-832065572045"
    bucket_path: "multi-docker"
    on:
      branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key:
      secure: "$AWS_SECRET_KEY"